import { User } from "./AdvancedTableOne";

// Mock data para ejemplos y pruebas
export const mockUsersData: User[] = [
  {
    id: 1,
    name: "Jese Leos",
    image: "/images/user/user-17.jpg",
    role: "Administrator",
    roleIcon: "👤",
    status: "Active",
    socialProfiles: ["instagram", "linkedin", "github"],
    promoted: false,
    rating: 4.7,
    ratingTrend: "up",
    lastLogin: "20 Nov 2022",
  },
  {
    id: 2,
    name: "Bonnie Green",
    image: "/images/user/user-18.jpg",
    role: "Viewer",
    roleIcon: "👁️",
    status: "Active",
    socialProfiles: ["instagram", "linkedin", "github"],
    promoted: true,
    rating: 3.9,
    ratingTrend: "down",
    lastLogin: "23 Nov 2022",
  },
  {
    id: 3,
    name: "Leslie Livingston",
    image: "/images/user/user-19.jpg",
    role: "Moderator",
    roleIcon: "⚡",
    status: "Inactive",
    socialProfiles: ["instagram", "linkedin"],
    promoted: false,
    rating: 4.8,
    ratingTrend: "up",
    lastLogin: "19 Nov 2022",
  },
  {
    id: 4,
    name: "Micheal Gough",
    image: "/images/user/user-20.jpg",
    role: "Moderator",
    roleIcon: "⚡",
    status: "Active",
    socialProfiles: ["instagram", "linkedin", "github"],
    promoted: true,
    rating: 5.0,
    ratingTrend: "up",
    lastLogin: "27 Nov 2022",
  },
  {
    id: 5,
    name: "Joseph McFall",
    image: "/images/user/user-21.jpg",
    role: "Viewer",
    roleIcon: "👁️",
    status: "Active",
    socialProfiles: ["linkedin", "github"],
    promoted: false,
    rating: 4.2,
    ratingTrend: "up",
    lastLogin: "20 Nov 2022",
  },
  {
    id: 6,
    name: "Robert Brown",
    image: "/images/user/user-22.jpg",
    role: "Viewer",
    roleIcon: "👁️",
    status: "Inactive",
    socialProfiles: ["instagram", "github"],
    promoted: false,
    rating: 4.5,
    ratingTrend: "up",
    lastLogin: "20 Nov 2022",
  },
  {
    id: 7,
    name: "Karen Nelson",
    image: "/images/user/user-23.jpg",
    role: "Viewer",
    roleIcon: "👁️",
    status: "Inactive",
    socialProfiles: ["instagram", "linkedin", "github"],
    promoted: false,
    rating: 4.1,
    ratingTrend: "up",
    lastLogin: "18 Nov 2022",
  },
  {
    id: 8,
    name: "Helene Engels",
    image: "/images/user/user-24.jpg",
    role: "Moderator",
    roleIcon: "⚡",
    status: "Active",
    socialProfiles: ["instagram", "linkedin", "github"],
    promoted: true,
    rating: 3.8,
    ratingTrend: "down",
    lastLogin: "27 Nov 2022",
  },
  {
    id: 9,
    name: "Lana Byrd",
    image: "/images/user/user-25.jpg",
    role: "Viewer",
    roleIcon: "👁️",
    status: "Active",
    socialProfiles: ["instagram", "linkedin"],
    promoted: false,
    rating: 4.6,
    ratingTrend: "up",
    lastLogin: "20 Nov 2022",
  },
  {
    id: 10,
    name: "Neil Sims",
    image: "/images/user/user-26.jpg",
    role: "Moderator",
    roleIcon: "⚡",
    status: "Inactive",
    socialProfiles: ["linkedin", "github"],
    promoted: false,
    rating: 5.0,
    ratingTrend: "up",
    lastLogin: "20 Nov 2022",
  },
];
